
services:
    db:
        image: mysql:latest
        container_name: db
        ports:
            - ${DATABASE_PORT:-3306}:3306
        volumes:
            - ./data/service-core-db:/var/lib/mysql
        networks:
            - service-core-backend
        healthcheck:
            test: "exit 0"
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}

    migrate:
        build:
            context: .
            dockerfile: Dockerfile.migrate
        container_name: migrate
        volumes:
            - .:/app
        env_file: .env
        depends_on:
            db:
                condition: service_started
        networks:
            - service-core-backend
        environment:
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_HOST: ${DATABASE_HOST}
        
        command: [
            "-path", "./internal/store/store/migrations",
            "-database", "mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@tcp(${DATABASE_HOST}:${DATABASE_PORT})/${DATABASE_NAME}",
            "up"
        ]
    app:
        build: .
        ports:
            - 3000:3000
        container_name: app
        volumes:
            - .:/app
        develop:
            watch:
                - action: sync
                  path: ./
                  target: /app
                  ignore:
                    - data/
                
        
        depends_on:
            - migrate
        networks:
            - service-core-backend
        environment:
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_HOST: db # Alterado para db, o nome do container do banco.
        


    mysqladmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: unless-stopped
        container_name: mysqladmin
        depends_on:
            - db
            - migrate
        ports:
            - 8081:80
        networks:
            - service-core-backend
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: ${DATABASE_USER}
            PMA_PASSWORD: ${DATABASE_PASSWORD}

networks:
    service-core-backend:
        driver: "bridge"    

volumes:
    mysql_data:
     driver: local