
services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - ${DATABASE_PORT:-3306}:3306
    volumes:
      - ./data/service-core-db:/var/lib/mysql
    networks:
      - service-core-backend
    healthcheck:
      test: "exit 0"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}  # Senha do root
      MYSQL_DATABASE: ${DATABASE_NAME}                # Nome do banco
      MYSQL_USER: ${DATABASE_USER}                    # Nome do usuário
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}            # Senha do usuário

  migrate:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: migrate
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_started
    networks:
      - service-core-backend
    environment:
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
    
    command: ["sh", "-c", "sleep 5 && migrate -path", "/migrations", "-database", "mysql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME", "up"]
    


  app:
    build: .
    ports:
      - 3000:3000
    container_name: app
    volumes:
      - .:/app
    depends_on:
      - migrate
    networks:
      - service-core-backend
    environment:
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}

  mysqladmin:
    image: phpmyadmin/phpmyadmin:latest   # Use o PhpMyAdmin para gerenciar o MySQL
    restart: unless-stopped
    container_name: mysqladmin
    depends_on:
      - db
      - migrate
    ports:
      - 8081:80
    networks:
      - service-core-backend
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DATABASE_USER}
      PMA_PASSWORD: ${DATABASE_PASSWORD}

networks:
  service-core-backend:
    driver: "bridge"

volumes:
  mysql_data:
    driver: local
